### ISSUE TITLE
Add Honeybadger

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_rails_api#23]
https://docs.honeybadger.io/lib/ruby/getting-started/introduction/

**Comment by maxkadel** [comment]
Currently successfully reporting deployments for both staging and production, but not errors. 

My suspicion is that it has to do with how Datadog is configuring the logs (they look very different from regular rails logs), but I could be wrong.

Current log line:
```
I, [2023-09-18T13:17:18.088413 #341184]  INFO -- : [e9af9eba-9716-41f4-b8b7-515afb996ff2] [dd.env=staging dd.service=allsearch-backend dd.trace_id=2362088655754469734 dd.span_id=0 ddsource=ruby] Started GET "/" for 127.0.0.1 at 2023-09-18 13:17:18 +0000
```

Example error from Orangelight logs
```
{"method":"GET","path":"/advanced","format":"html","controller":"AdvancedController","action":"index","status":500,"error":"Blacklight::Exceptions::InvalidRequest: RSolr::Error::Http - 400 Bad Request\nError: Pivot Facet needs at least one field name: \n\nURI: http://127.0.0.1:51939/solr/orangelight-core-dev/select?wt=json\nRequest Headers: {\"Content-Type\"=>\"application/json\"}\nRequest Data: \"{\\\"params\\\":{\\\"qt\\\":null,\\\"facet\\\":true,\\\"facet.field\\\":[\\\"access_facet\\\",\\\"format\\\",\\\"language_facet\\\",\\\"advanced_location_s\\\"],\\\"f.access_facet.facet.sort\\\":\\\"index\\\",\\\"f.location.facet.sort\\\":\\\"index\\\",\\\"f.location.facet.mincount\\\":1,\\\"f.location.facet.limit\\\":21,\\\"f.format.facet.sort\\\":\\\"index\\\",\\\"f.format.facet.mincount\\\":1,\\\"f.format.facet.limit\\\":16,\\\"f.language_facet.facet.limit\\\":-1,\\\"f.subject_topic_facet.facet.limit\\\":11,\\\"f.genre_facet.facet.limit\\\":11,\\\"f.subject_era_facet.facet.limit\\\":11,\\\"facet.query\\\":\\\"\\\",\\\"f.instrumentation_facet.facet.limit\\\":11,\\\"f.publication_place_facet.facet.limit\\\":11,\\\"facet.pivot\\\":\\\"\\\",\\\"f.sudoc_facet.facet.sort\\\":\\\"index\\\",\\\"f.sudoc_facet.facet.limit\\\":11,\\\"rows\\\":\\\"0\\\",\\\"sort\\\":\\\"score desc, pub_date_start_sort desc, title_sort asc\\\",\\\"stats\\\":\\\"true\\\",\\\"stats.field\\\":[\\\"pub_date_start_sort\\\"],\\\"q\\\":\\\"{!lucene}*:*\\\",\\\"defType\\\":\\\"lucene\\\",\\\"facet.limit\\\":-1,\\\"f.language_facet.facet.sort\\\":\\\"index\\\"},\\\"query\\\":{\\\"bool\\\":{\\\"must\\\":[{\\\"edismax\\\":{\\\"query\\\":\\\"gay\\\"}}]}}}\"\n\nBacktrace: /Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:220:in `rescue in execute'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:208:in `execute'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:203:in `send_and_receive'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/lib/blacklight/solr/repository.rb:61:in `block in send_and_receive'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/benchmarkable.rb:43:in `block in benchmark'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/benchmark-0.2.1/lib/benchmark.rb:311:in `realtime'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/benchmarkable.rb:43:in `benchmark'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/lib/blacklight/solr/repository.rb:60:in `send_and_receive'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/lib/blacklight/solr/repository.rb:23:in `search'\n/Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/blacklight-7.33.1/app/services/blacklight/search_service.rb:33:in `search_results'","duration":79.81,"view":0.0,"db":20.55,"unpermitted_params":["utf8"],"ddsource":["ruby"],"@timestamp":"2023-08-24T12:52:58.761Z","@version":"1","message":"[500] GET /advanced (AdvancedController#index)"}
```

**Comment by maxkadel** [comment]
Successfully raised error by putting a "raise" in deployed code.
